<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="7" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="56218" started-at="2020-12-08T15:01:25 IST" finished-at="2020-12-08T15:02:21 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="56218" started-at="2020-12-08T15:01:25 IST" finished-at="2020-12-08T15:02:21 IST">
      <class name="banker_Login_Testcase.Run_Banker_login">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:banker_Login_Testcase.Run_Banker_login@6321e813]" name="beforeClass" is-config="true" duration-ms="6253" started-at="2020-12-08T15:01:25 IST" finished-at="2020-12-08T15:01:31 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="Tc021_Login_As_Banker()[pri:0, instance:banker_Login_Testcase.Run_Banker_login@6321e813]" name="Tc021_Login_As_Banker" duration-ms="9222" started-at="2020-12-08T15:01:31 IST" finished-at="2020-12-08T15:01:40 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Tc021_Login_As_Banker -->
        <test-method status="PASS" signature="afterMethod(java.lang.reflect.Method)[pri:0, instance:banker_Login_Testcase.Run_Banker_login@6321e813]" name="afterMethod" is-config="true" duration-ms="496" started-at="2020-12-08T15:01:40 IST" finished-at="2020-12-08T15:01:41 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void banker_Login_Testcase.Run_Banker_login.Tc021_Login_As_Banker()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="TC022_verify_account_details_displayed_using_valid_account_number()[pri:1, instance:banker_Login_Testcase.Run_Banker_login@6321e813]" name="TC022_verify_account_details_displayed_using_valid_account_number" duration-ms="1410" started-at="2020-12-08T15:01:41 IST" depends-on-methods="banker_Login_Testcase.Run_Banker_login.Tc021_Login_As_Banker" finished-at="2020-12-08T15:01:42 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at banker_Login_Testcase.banker_tests.Receipts_DD_Deposit_using_Valid_AccoutNumber(banker_tests.java:51)
at banker_Login_Testcase.Run_Banker_login.TC022_verify_account_details_displayed_using_valid_account_number(Run_Banker_login.java:56)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC022_verify_account_details_displayed_using_valid_account_number -->
        <test-method status="PASS" signature="afterMethod(java.lang.reflect.Method)[pri:0, instance:banker_Login_Testcase.Run_Banker_login@6321e813]" name="afterMethod" is-config="true" duration-ms="369" started-at="2020-12-08T15:01:42 IST" finished-at="2020-12-08T15:01:43 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void banker_Login_Testcase.Run_Banker_login.TC022_verify_account_details_displayed_using_valid_account_number() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="TC023_verify_alert_displayed_using_invalid_account_number()[pri:2, instance:banker_Login_Testcase.Run_Banker_login@6321e813]" name="TC023_verify_alert_displayed_using_invalid_account_number" duration-ms="5675" started-at="2020-12-08T15:01:43 IST" depends-on-methods="banker_Login_Testcase.Run_Banker_login.Tc021_Login_As_Banker" finished-at="2020-12-08T15:01:48 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC023_verify_alert_displayed_using_invalid_account_number -->
        <test-method status="PASS" signature="afterMethod(java.lang.reflect.Method)[pri:0, instance:banker_Login_Testcase.Run_Banker_login@6321e813]" name="afterMethod" is-config="true" duration-ms="383" started-at="2020-12-08T15:01:48 IST" finished-at="2020-12-08T15:01:49 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void banker_Login_Testcase.Run_Banker_login.TC023_verify_alert_displayed_using_invalid_account_number() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="Tc_024_Verify_DD_Deposit()[pri:3, instance:banker_Login_Testcase.Run_Banker_login@6321e813]" name="Tc_024_Verify_DD_Deposit" duration-ms="10099" started-at="2020-12-08T15:01:49 IST" depends-on-methods="banker_Login_Testcase.Run_Banker_login.Tc021_Login_As_Banker" finished-at="2020-12-08T15:01:59 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Tc_024_Verify_DD_Deposit -->
        <test-method status="PASS" signature="afterMethod(java.lang.reflect.Method)[pri:0, instance:banker_Login_Testcase.Run_Banker_login@6321e813]" name="afterMethod" is-config="true" duration-ms="330" started-at="2020-12-08T15:01:59 IST" finished-at="2020-12-08T15:01:59 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void banker_Login_Testcase.Run_Banker_login.Tc_024_Verify_DD_Deposit() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="Tc_025_Verify_Cheque_Deposit()[pri:4, instance:banker_Login_Testcase.Run_Banker_login@6321e813]" name="Tc_025_Verify_Cheque_Deposit" duration-ms="1265" started-at="2020-12-08T15:01:59 IST" depends-on-methods="banker_Login_Testcase.Run_Banker_login.Tc021_Login_As_Banker" finished-at="2020-12-08T15:02:00 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at banker_Login_Testcase.banker_tests.Receipts_Cheque_Deposit_using_Valid_AccoutNumber(banker_tests.java:106)
at banker_Login_Testcase.Run_Banker_login.Tc_025_Verify_Cheque_Deposit(Run_Banker_login.java:87)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Tc_025_Verify_Cheque_Deposit -->
        <test-method status="PASS" signature="afterMethod(java.lang.reflect.Method)[pri:0, instance:banker_Login_Testcase.Run_Banker_login@6321e813]" name="afterMethod" is-config="true" duration-ms="332" started-at="2020-12-08T15:02:00 IST" finished-at="2020-12-08T15:02:01 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void banker_Login_Testcase.Run_Banker_login.Tc_025_Verify_Cheque_Deposit() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="TC026_verify_account_details_displayed_using_valid_account_number()[pri:5, instance:banker_Login_Testcase.Run_Banker_login@6321e813]" name="TC026_verify_account_details_displayed_using_valid_account_number" duration-ms="646" started-at="2020-12-08T15:02:01 IST" depends-on-methods="banker_Login_Testcase.Run_Banker_login.Tc021_Login_As_Banker" finished-at="2020-12-08T15:02:01 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC026_verify_account_details_displayed_using_valid_account_number -->
        <test-method status="PASS" signature="afterMethod(java.lang.reflect.Method)[pri:0, instance:banker_Login_Testcase.Run_Banker_login@6321e813]" name="afterMethod" is-config="true" duration-ms="257" started-at="2020-12-08T15:02:01 IST" finished-at="2020-12-08T15:02:02 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void banker_Login_Testcase.Run_Banker_login.TC026_verify_account_details_displayed_using_valid_account_number() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="Tc_027_Verify_Cash_Withdraw()[pri:6, instance:banker_Login_Testcase.Run_Banker_login@6321e813]" name="Tc_027_Verify_Cash_Withdraw" duration-ms="8912" started-at="2020-12-08T15:02:02 IST" depends-on-methods="banker_Login_Testcase.Run_Banker_login.Tc021_Login_As_Banker" finished-at="2020-12-08T15:02:11 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Tc_027_Verify_Cash_Withdraw -->
        <test-method status="PASS" signature="afterMethod(java.lang.reflect.Method)[pri:0, instance:banker_Login_Testcase.Run_Banker_login@6321e813]" name="afterMethod" is-config="true" duration-ms="328" started-at="2020-12-08T15:02:11 IST" finished-at="2020-12-08T15:02:11 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void banker_Login_Testcase.Run_Banker_login.Tc_027_Verify_Cash_Withdraw() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:banker_Login_Testcase.Run_Banker_login@6321e813]" name="afterClass" is-config="true" duration-ms="10166" started-at="2020-12-08T15:02:11 IST" finished-at="2020-12-08T15:02:21 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- banker_Login_Testcase.Run_Banker_login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
